name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  schedule:  # at 03:06 on day-of-month 11
    - cron: '6 3 11 * *'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        dotnet-version: ['6.0.x', '8.0.x', '9.0.x']

    steps:
    - uses: actions/checkout@v4
    - name: Install OpenSSL 1.1
      run: |
        wget http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.23_amd64.deb
        sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2.23_amd64.deb
    - name: Setup .NET 5.0.x
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '5.0.x'
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Run tests on Windows after setting HOME environment variable
      if: ${{ matrix.os == 'windows-latest' }}
      run: |
        $env:HOME = $env:HOMEPATH
        echo "Set HOME to $HOME"
        cd RedDove.Config
        dotnet build
        cd ../RedDove.Config.Test
        dotnet test
    - name: Run tests on POSIX
      if: ${{ matrix.os != 'windows-latest' }}
      run: |
        cd RedDove.Config
        dotnet build
        cd ../RedDove.Config.Test
        dotnet test
